# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b631618d7ea14253fafc6f6ad5136e3e79c5ebca3ebda0bdb4c07681ac96213466787fc9d95ca290b41bd5dfff94dd35f8c57b870cbda79846732fc694eaa6

test:
  secret_key_base: d019580fb56c2682a55a12348e12329b606fbffe2f1ee5e850f0051867e0586986a646092db8ea2b25bcf46da2a93dc3f77b1462953cfd5047b617d59f117c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
